// Finally runs in every case, with error or without error

try {
    let a = 1;
    // console.log(z)
    console.log("Success")
    // it runs if we have return
    // return
} catch (error) {
    console.log("This is error")
}

finally{
    console.log("Finally Clause")
}